FROM anapsix/alpine-java
MAINTAINER Matthias Milan Strljic
ENV TEAM TEAM-Mathi
COPY ./target/best-qrcode-service-cloud-1.0-SNAPSHOT-spring-boot.jar best-qrcode-service-cloud-1.0-SNAPSHOT-spring-boot.jar
CMD java -jar best-qrcode-service-cloud-1.0-SNAPSHOT-spring-boot.jar $TEAM